name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    sync-to-hub:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Add remote
          env: 
            HG_FACE: ${{ secrets.HG_FACE }}
          run: git remote add space https://eveval97:$HG_FACE@huggingface.co/spaces/eveval97/text_summarization
        - name: Push to hub
          env: 
            HG_FACE: ${{ secrets.HG_FACE }}
          run: git push --force https://eveval97:$HG_FACE@huggingface.co/spaces/eveval97/text_summarization main
        
  # This workflow contains a single job called "build"
